name: Publish to npm (manual)

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Publication type (latest = normal, beta = beta version)"
        required: true
        default: "latest"
        type: choice
        options:
          - latest
          - beta
      version:
        description: "Package version (e.g., 2.0.0 or 2.0.0-beta.5)"
        required: true
        default: "2.0.0"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org/"

      - name: Set version
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          npm version ${{ github.event.inputs.version }}
          git push origin --follow-tags

      - name: Install dependencies
        run: npm ci

      #      - name: Build package
      #        run: npm run build --if-present

      - name: Publish to npm
        run: |
          if [ "${{ github.event.inputs.release_type }}" = "beta" ]; then
            npm publish --tag beta
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
